name: jaguar_flutter_asset
description: Serve files from Flutter assets.
version: 2.1.1
author: Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_flutter_asset

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  jaguar: 2.1.38

flutter: